name: Master branch
on:
  pull_request:
    types: closed
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: tool3/bump@v.1.2
      id: bump
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
