name: Master branch
on:
  pull_request:
    types: closed
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Github Bot
      id: changelog
      uses: TriPSs/conventional-changelog-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: 'false'
        tag-prefix: ''
    - name: changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.Changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
