name: Master branch
on:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/bump@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: 'First Last'
          email: 'user.email@gmail.com'
