name: Master branch
on:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: tool3/bump@master
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
